### ISSUE TITLE
Update notebook

### ISSUE THREAD

**Issue by OBrink** [hannbus/ChemIcal_DatasEt_compaRator#4]
## Required modifications:
- delete function definitions from notebook
- adapt all examples in the notebook to use the ChemicalDatasetComparator class methods

**Comment by JonasSchaub** [comment]
Also, rename the notebook. I would propose "CIDER-Workflow" or something like it. After a bit of consideration, I would not like to call it "Tutorial" because the original idea was not to have a package but a ready-to-use workflow with visualisations where I only have to set the directory path to my datasets and execute the whole notebook to see the results. Therefore, we should put the notebook more into focus again and not simply label it as a tutorial.

**Comment by hannbus** [comment]
The function definitions are now deleted from the notebook. But I am not sure if the called the functions the right way (I copied the cider.py file from main into my own branch in working dictionary of the notebook and used 'from cider import function' for every function I needed).
I also renamed the notebook to 'CIDER_Workflow'.
I noticed that there is a error in the function definition of 'continuous_descriptor_plot'. In the function I accidentally wrote 'Testdict' although it has to be 'all_dicts'. I changed this in my copy of cider.py to make it work in the notebook, but ultimately it has to be changed in the original cider.py file as well.

**Comment by OBrink** [comment]
Damn. It appears like you did not pull from the main branch before making all of these changes. This is a bit problematic as you are now working with the old version of cider.py. The updated cider.py is unfortunately not compatible with what you have done since I wrote the wrapper class. When you look at the file import in the main branch, there is an example of how to use the CIDER methods with the wrapper class.
- About copying cider.py into the directory of the notebook: This means that you have not pip-installed CIDER! Please delete the file in the notebook directory and run "pip install ." from the root directory of the repository. This will install CIDER as a package and you can then "import CIDER" independent of where the file that executes it is. 
- It would be great if you could have a look in the notebook again and adapt it according to the cider.py version in the main branch. The wrapper class has been written in order to avoid global variables and keep them available. The global variable definitions in the notebook of your branch have no meaning right now. I could change them to whatever I want and it would not have an influence because, in the old version, all global variables are defined in cider.py. In the new version, they are class attributes that the user can change from everywhere. 

Text me if anything is unclear! :)

**Comment by hannbus** [comment]
I just updated my branch with the recent version of main and deleted the cider.py file from the notebook directory, so everything should be up to date now. After that I followed the installation remarks and created a complete new conda environment . But if I now try to import CIDER in the notebook I get an error "DLL load failed while importing rdBase: Das angegebene Modul wurde nicht gefunden." Do you maybe know what I did wrong or how to solve this?

**Comment by OBrink** [comment]
That seems to be the same issue that Jonas ran into (https://github.com/hannbus/ChemIcal_DatasEt_compaRator/issues/3). I would recommend the conda installation of RDKit on Windows. We should change the installation instructions in the readme.

**Comment by JonasSchaub** [comment]
That sounds very good, Hannah!

For the installation: in the other issue that Otto linked, I got the Windows installation working in the end and described how I did it. Can you test that? When Kohulan is back, we might change the installation guidelines accordingly.

And when you import CIDER like this (with "pip install . " in the repository directory as final call), you should not have to import all the CIDER functions individually, as Otto has been saying. 

Proceeding with this issue: Could you also
- rename the folder where the notebook is located accordingly
- get rid of the output folder (delete it and add it to the gitignore)

**Comment by hannbus** [comment]
Following the installation how you described worked for me. 
Even though 'import CIDER' also does not give an error in the notebook, if I try to call a function I get 'NameError: name 'import_as_data_dict' is not defined'. 'From CIDER import ...' also did not work and gives 'ImportError: cannot import name 'import_as_data_dict' from 'CIDER''. Has one of you ever tried to run CIDER in a notebook to see if it works for you? Or do you know what the problem now is?

**Comment by OBrink** [comment]
Did you try to use it with the wrapper class as described in the first example in the [notebook in the main branch](https://github.com/hannbus/ChemIcal_DatasEt_compaRator/blob/main/Tutorials/Praktikum_V3.ipynb)?
The idea is that every method is wrapped up in the ChemicalDatasetComparator class. The variables are attributes of an instance of this class.

`from CIDER import import_as_data_dict`
fails because the method "import_as_data_dict" does not exist outside of this class. The following way, it should work:

We have to import the ChemicalDatasetComparator class from CIDER:
`from CIDER import ChemicalDatasetComparator`
Then, we need to instanciate an object of this class:
`cider = ChemicalDatasetComparator()`
Now, we can access the methods:
`testdict = cider.import_as_data_dict('data2')`

The advantage of this approach is that the user can access and manipulate all the values that previously were defined as global variables because they also belong to this object:
`print(cider.import_keyname)`

I hope this helps! If you want to meet up to talk about it, let me know :)

**Comment by JonasSchaub** [comment]
Thank you, We'll have a look at it! :)

**Comment by JonasSchaub** [comment]
Dear Hannah,

first of all, I did a complete "re-installation" of the repository and the CIDER conda environment and everything is working like a charm (even on Windows), wonderful! :)

Here are "a few" comments on the notebook and the  cider code:

- In the Notebook as a presentable example workflow of CIDER, we should work more with markdown cells to make it "pretty". First of all, the notebook needs a markdown title cell. Below that, I would put our nice short description and a note saying "for details on the individual methods and their handling, refer to the documentation". Then, above every code cell, there should be a short description on what is done in the cell below (can be copied from your code documentation in most cases, I guess). 
- Also for better "documentation": I would insert a cell at the beginning printing and describing the class variables that cider has, i.e. the different keys and stuff. 
- This is a question of style, but I think that functions like "get_number_of_molecules" or "get_database_id" do not need to return the input dictionary again. Since they directly update the dictionary that is given to them. To "proof" that it has been updated, rather access it directly after the function call in the notebook via the defined variable that represents it. This is also a nice way of showcasing how to access the different data fields in the dictionary.
- directly relating from the last point: The dict data structure that you are building can be confusing in the first moment. Which is why a few examples on how to access different fields in the dict (without the one cider function that you have for this) would be nice. E.g. how do I access the data of only one data set, one specific molecule, etc.
- For methods like "get_database_id", the printout of the whole data "clogs" the notebook. Rather print a few entries (like this "head" function that can be applied to pandas dataframes) to "proof" that the data is there.
- So far, you have been working with well-curated data. But in "the real world", your code will encounter many unforeseen things and definitely less well curated data. Which is why the cider functions need more try-except blocks internally. The important things is: One faulty molecule should not lead to the whole function crashing. This means that when you iterate over molecules and do something with them, the loop body (not the whole loop) should be in a try-except block that simply skips the molecule if it is faulty.
- I would separate the descriptor plots into different cells.
- I guess there is a reason why the chemical space plot is set to interactive=false? Or could we set this back to true? It would also be nice to directly below do the same with the other dimensionality reduction options. To be able to compare the results side-by-side because they tend to be very differently.
- The exported versions of the "draw_molecules" grid figures do not have titles which is especially sad because they therefore also don't have titles in the PDF report. 

If you have any questions or want to discuss things in a meeting, I'm always up for it!
And of course, only start working on this next month, when your contract has officially started ;)

**Comment by hannbus** [comment]
I updated the workflow considering your comments. Therefore, I also changed some things in the cider.py file but the tests are still  passed and everything works in the notebook. 
The default value for the chemical space plot is now interactive=True but the plot will not be shown in line. The reason for setting it to false was that it is way faster when running.
I'm not sure what there should be about the class variables, so maybe you can comment on that?
Next I will work on try-except blocks (and updating the test functions).
When you have time you can take a look at the whole notebook.

**Comment by OBrink** [comment]
I will have a deeper look at everything later. The notebook looks very neat to me now. 
___
About the class attributes: It would make sense to add information about what possible values a user can set. Right now, we have a set of predefined values. A user who opens the notebook does not know what options they have. I think that we should add this information.

**Comment by JonasSchaub** [comment]
Regarding the class variables, the most important bit of information that needs to be documented there is what the respective class variable is used for, i.e. in what method for what purpose. And after that, yes, come the possible other values for these variables, like e.g. setting another property key for the database id.

And same as Otto, I will have a look at everything when I find the time ;)

Thank you very much so far!

**Comment by hannbus** [comment]
Now the Notebook is pretty much up to date and I added the test functions for the private functions.
I also added a new function at the beginning to find faulty molecules in the SDFiles giving the option to delete them from the dataset. Additionally, I started adding try-except blocks in the functions .
Maybe for the next steps you could send me the work done by Muhlise about the scaffold analysis? I could than implement it as a new function in Cider and add the corresponding test.

**Comment by JonasSchaub** [comment]
Hi Hannah,
that sounds very nice, thank you! 
I will send you the scaffold work via e-mail 👍

**Comment by Kohulan** [comment]
@hannbus and @JonasSchaub ,
Have a look at this: https://github.com/PatWalters/practical_cheminformatics_tutorials
Specially this one: https://colab.research.google.com/github/PatWalters/practical_cheminformatics_tutorials/blob/main/sar_analysis/find_scaffolds.ipynb

**Comment by JonasSchaub** [comment]
@Kohulan a bit different in detail but close to what I wanted to achieve, yes, thank you!

**Comment by OBrink** [comment]
Hey @hannbus! Thank you for all of the work. 

One general remark regarding try-except-blocks. It would normally be considered to be good practice to know exactly what is going on in the code. An error/exception that is thrown can be specifically handled by a block. But it is considered bad practice to write generic try-except blocks that catch every potential error. If possible, I would try to avoid them as they might hide errors in the code.

In cider.py, line 71ff: 
```            
for mol in all_dicts[single_dict][self.import_keyname]:
    try:
        mol_index +=1
        assert mol
    except:
        pass
        print(str(single_dict) + ' has invalid molecule at index ' + str(mol_index))
        invalid_index.append(mol_index)
```

could easily be replaced with the following code snippet that does the exact same thing without using a try-except block:

```            
for mol in all_dicts[single_dict][self.import_keyname]:
    mol_index +=1
    if not mol:
        print(str(single_dict) + ' has invalid molecule at index ' + str(mol_index))
        invalid_index.append(mol_index)
```

In a similar manner, the try-except block in line 210ff could be avoided by running "if mol" before trying to do something with it. Please remove these try-except blocks. 

Once that's done, I would close this issue and open a new one for the discussion about the scaffold analysis.

**Comment by JonasSchaub** [comment]
I agree, the scaffold analysis is a new enhancement that should be discussed in a separate issue. Please see the email I just sent to everyone.

**Comment by hannbus** [comment]
I removed the try-except blocks.

**Comment by OBrink** [comment]
Thank you! I have merged your branch with the main branch of the repository.
